# Generated by Django 3.2.25 on 2025-02-20 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20250220_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='TripPost',
        ),
    ]
