# Generated by Django 3.2.25 on 2025-02-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0004_rename_post_trippost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_number', models.PositiveIntegerField()),
                ('relevant_for', models.CharField(choices=[('all', 'All Genders & Orientations'), ('women', 'Women'), ('men', 'Men'), ('nonbinary', 'Non-Binary'), ('lgbtq', 'LGBTQ+ Travelers')], max_length=10)),
                ('duration_value', models.PositiveBigIntegerField()),
                ('duration_unit', models.CharField(choices=[('days', 'Day(s)'), ('weeks', 'Week(s)'), ('months', 'Month(s)'), ('years', 'Year(s)')], max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.region')),
                ('trip_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='posts.trippost')),
            ],
        ),
    ]
