# Generated by Django 3.2.25 on 2025-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0005_tripdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='city',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='city',
            field=models.ManyToManyField(to='cities_light.City'),
        ),
    ]
