# Generated by Django 3.2.25 on 2025-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20250221_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdetails',
            old_name='city',
            new_name='cities',
        ),
    ]
