# Generated by Django 3.2.25 on 2025-02-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_city_tripdetails_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='region',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='continent',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
