# Generated by Django 3.2.25 on 2025-02-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0008_auto_20250221_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='cities',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city'),
        ),
    ]
