# Generated by Django 3.2.25 on 2025-03-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_trippost_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippost',
            name='image',
            field=models.ImageField(default='../default_post_hrftao', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trippost',
            name='image_alt_text',
            field=models.CharField(help_text='Please describe your image in case              there is an issue displaying it.', max_length=255),
        ),
    ]
