# Generated by Django 3.2.25 on 2025-03-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20250302_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippost',
            name='image_filter',
        ),
    ]
