# Generated by Django 3.2.25 on 2025-03-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('posts', '0013_remove_trippost_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='city',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
    ]
