# Generated by Django 3.2.25 on 2025-04-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20250318_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='duration_value',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('10+', '10+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='traveller_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('10+', '10+')], max_length=3),
        ),
    ]
